### PR TITLE
fix type declaration highlighting on single line.

### PR DESCRIPTION
**Pull request by PhilipWitte**
make 'concept' keyword appear alphabetically.

### CODE REVIEW

**Comment by PhilipWitte** [comment]
Don't pull this yet, I have a few more changes on my local drive to commit first.

**Comment by dom96** [comment]
@PhilipWitte ping me when it's done.

**Comment by PhilipWitte** [comment]
@dom96 go ahead and pull it now. I need to eventually adjust the "command" regex a tad more in the future, but for now my latest commit handles most scenarios well.

**Comment by dom96** [comment]
Apologies for the delay.

**Comment by PhilipWitte** [comment]
No worries, needed the time to improve the PR anyways.

**Pull request merged**
